### ISSUE TITLE
No visible @interface for 'SIOSocket' declares the selector 'on:do:' in the example.

### ISSUE THREAD

**Issue by AndrusAsumets** [MegaBits/WorldPin#2]
Hi,

Although I've got experience with running node.js in the backend [1], I'm unfortunately new to iOS.

I git cloned the example app, did "sudo gem install cocoapods" as well as "pod install" in the app folder. However, I'm getting "No visible @interface for 'SIOSocket' declares the selector" on all of the "on" functions like @"join", @"update" and on @"disappear" in Xcode 5.1.1. Screenshot [2].

When I commented the code out from those methods I could see that the app is connecting to the node.js instance, and the iOS Simulator runs perfectly.

Sorry for my ignorance, but what am I missing?

Best,
Andrus

[1] - http://sync.club/#wir3d
[2] - https://www.dropbox.com/s/ooaxz3iqcaso80r/50.png?dl=0

**Comment by Thunderr** [comment]
I have the same issue.
Just replace "do" parameter to "callback" according to class definition....
[self.socket on: @"update" callback: ^(id pinData) ....]
